POST https://football-api-challenge-admin-mohsenxad.fandogh.cloud/challenge/add
Content-Type: application/json

{
  "event": "63627a551227fc3ff8ecf73c",
  "title":"برنده مسابقه",
  "startDateTime":"1667048780939",
  "endDateTime":"1667048780990",
  "optionList":[
        {
        "title":"کامرون"
        },
        {
        "title":"برزیل"
        },
        {
        "title":"مساوی"
        }
    ]
  
}